/*
 * Copyright 2012 Net4Care, www.net4care.org
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */ 
 
package org.net4care.receiver; 
 
import java.util.Map; 
 
import org.net4care.observation.StandardTeleObservation; 
import org.net4care.utility.Net4CareException; 
 
/** The receiver of messages (on the server side) 
 * generated by the Home devices. 
 *  
 * Acts as the Receiver of the Forwarder-Receiver 
 * pattern in POSA 1, p. 307. 
 *  
 * @author Henrik Baerbak Christensen, Aarhus University 
 * 
*/ 
import com.apkc.archtype.quals.*;
@ArchTypeComponent(
          patterns = {@Pattern(name="testLayered", kind = "Layered", role="Layer{1}")}
          ) 
public interface ObservationReceiver { 
 
	/** Invoked by the server process once a valid 
	 * observation message has arrived 
	 * @param messagePayload the message from the home device containing 
	 * a StandardTeleObservation in the adopted on-the-wire format. 
	 * See the Serializer interface. 
	 * @throws UnknownCPRException  
	 * @throws Net4CareException  
	 */ 
	public StandardTeleObservation observationMessageReceived(String messagePayload) throws Net4CareException; 
 
	/** Invoked by the server process once a query has arrived.  
	 * Must return the serialized form of the list of observations. 
	 * @param query a (key,value) map of the required fields of the 
	 * query, see the description in interface Query. 
	 * @return a string containing a serialized form of an array 
	 * containing all observations in their serialized form. See 
	 * the Serializer interface. 
	 */ 
  public String observationQueryReceived(Map<String,String> query) throws Net4CareException; 
	 
} 
