/*
 * Copyright 2012 Net4Care, www.net4care.org
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */ 
 
// 
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5  
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>  
// Any modifications to this file will be lost upon recompilation of the source schema.  
// Generated on: 2012.04.17 at 09:07:48 PM MAGST  
// 
 
 
package oasis.names.tc.ebxml_regrep.xsd.rim._3; 
 
import javax.xml.bind.annotation.XmlAccessType; 
import javax.xml.bind.annotation.XmlAccessorType; 
import javax.xml.bind.annotation.XmlAttribute; 
import javax.xml.bind.annotation.XmlElement; 
import javax.xml.bind.annotation.XmlType; 
 
 
/** 
 * Notification of registry events. 
 *  
 * <p>Java class for NotificationType complex type. 
 *  
 * <p>The following schema fragment specifies the expected content contained within this class. 
 *  
 * <pre> 
 * &lt;complexType name="NotificationType"> 
 *   &lt;complexContent> 
 *     &lt;extension base="{urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0}RegistryObjectType"> 
 *       &lt;sequence> 
 *         &lt;element ref="{urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0}RegistryObjectList"/> 
 *       &lt;/sequence> 
 *       &lt;attribute name="subscription" use="required" type="{urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0}referenceURI" /> 
 *     &lt;/extension> 
 *   &lt;/complexContent> 
 * &lt;/complexType> 
 * </pre> 
 *  
 *  
 */ 
@XmlAccessorType(XmlAccessType.FIELD) 
@XmlType(name = "NotificationType", propOrder = { 
    "registryObjectList" 
}) 
public class NotificationType 
    extends RegistryObjectType 
{ 
 
    @XmlElement(name = "RegistryObjectList", required = true) 
    protected RegistryObjectListType registryObjectList; 
    @XmlAttribute(name = "subscription", required = true) 
    protected String subscription; 
 
    /** 
     * Gets the value of the registryObjectList property. 
     *  
     * @return 
     *     possible object is 
     *     {@link RegistryObjectListType } 
     *      
     */ 
    public RegistryObjectListType getRegistryObjectList() { 
        return registryObjectList; 
    } 
 
    /** 
     * Sets the value of the registryObjectList property. 
     *  
     * @param value 
     *     allowed object is 
     *     {@link RegistryObjectListType } 
     *      
     */ 
    public void setRegistryObjectList(RegistryObjectListType value) { 
        this.registryObjectList = value; 
    } 
 
    /** 
     * Gets the value of the subscription property. 
     *  
     * @return 
     *     possible object is 
     *     {@link String } 
     *      
     */ 
    public String getSubscription() { 
        return subscription; 
    } 
 
    /** 
     * Sets the value of the subscription property. 
     *  
     * @param value 
     *     allowed object is 
     *     {@link String } 
     *      
     */ 
    public void setSubscription(String value) { 
        this.subscription = value; 
    } 
 
} 
