/*
 * Copyright 2012 Net4Care, www.net4care.org
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */ 
 
package org.net4care.xdsproxy; 
 
import java.io.File; 
import java.util.HashMap; 
 
import org.apache.axis.message.SOAPBodyElement; 
import org.tempuri.DocumentRepositoryServiceLocator; 
 
import com.microsoft.schemas.Message.MessageBody; 
 
/** A wrapper class around the AJAX XDSRepository autogenerated 
 * class, to allow injecting a test double. 
 * @author Henrik Baerbak Christensen, Net4Care, AU 
 * 
 */ 
public interface XDSRepositoryWrapper { 
 
  public void defineHTTPEndpoint() throws javax.xml.rpc.ServiceException; 
 
  public void setHeader(String namespace, String partName, String headerValue); 
 
  public MessageBody retrieveDocumentSet(MessageBody retriveDocument) throws java.rmi.RemoteException; 
 
  public MessageBody provideAndRegisterDocumentSet( 
      SOAPBodyElement provideAndRegister, 
      HashMap<FileMetaData, File> documentAttachments) throws java.rmi.RemoteException; 
 
} 
