/*
 * Copyright 2012 Net4Care, www.net4care.org
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */ 
 
// 
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5  
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>  
// Any modifications to this file will be lost upon recompilation of the source schema.  
// Generated on: 2012.04.17 at 09:07:48 PM MAGST  
// 
 
 
package oasis.names.tc.ebxml_regrep.xsd.rs._3; 
 
import javax.xml.bind.annotation.XmlAccessType; 
import javax.xml.bind.annotation.XmlAccessorType; 
import javax.xml.bind.annotation.XmlAttribute; 
import javax.xml.bind.annotation.XmlRootElement; 
import javax.xml.bind.annotation.XmlType; 
import javax.xml.bind.annotation.XmlValue; 
 
 
/** 
 * <p>Java class for anonymous complex type. 
 *  
 * <p>The following schema fragment specifies the expected content contained within this class. 
 *  
 * <pre> 
 * &lt;complexType> 
 *   &lt;simpleContent> 
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string"> 
 *       &lt;attribute name="codeContext" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /> 
 *       &lt;attribute name="errorCode" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /> 
 *       &lt;attribute name="severity" type="{urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0}referenceURI" default="urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:Error" /> 
 *       &lt;attribute name="location" type="{http://www.w3.org/2001/XMLSchema}string" /> 
 *     &lt;/extension> 
 *   &lt;/simpleContent> 
 * &lt;/complexType> 
 * </pre> 
 *  
 *  
 */ 
@XmlAccessorType(XmlAccessType.FIELD) 
@XmlType(name = "", propOrder = { 
    "value" 
}) 
@XmlRootElement(name = "RegistryError") 
public class RegistryError { 
 
    @XmlValue 
    protected String value; 
    @XmlAttribute(name = "codeContext", required = true) 
    protected String codeContext; 
    @XmlAttribute(name = "errorCode", required = true) 
    protected String errorCode; 
    @XmlAttribute(name = "severity") 
    protected String severity; 
    @XmlAttribute(name = "location") 
    protected String location; 
 
    /** 
     * Gets the value of the value property. 
     *  
     * @return 
     *     possible object is 
     *     {@link String } 
     *      
     */ 
    public String getValue() { 
        return value; 
    } 
 
    /** 
     * Sets the value of the value property. 
     *  
     * @param value 
     *     allowed object is 
     *     {@link String } 
     *      
     */ 
    public void setValue(String value) { 
        this.value = value; 
    } 
 
    /** 
     * Gets the value of the codeContext property. 
     *  
     * @return 
     *     possible object is 
     *     {@link String } 
     *      
     */ 
    public String getCodeContext() { 
        return codeContext; 
    } 
 
    /** 
     * Sets the value of the codeContext property. 
     *  
     * @param value 
     *     allowed object is 
     *     {@link String } 
     *      
     */ 
    public void setCodeContext(String value) { 
        this.codeContext = value; 
    } 
 
    /** 
     * Gets the value of the errorCode property. 
     *  
     * @return 
     *     possible object is 
     *     {@link String } 
     *      
     */ 
    public String getErrorCode() { 
        return errorCode; 
    } 
 
    /** 
     * Sets the value of the errorCode property. 
     *  
     * @param value 
     *     allowed object is 
     *     {@link String } 
     *      
     */ 
    public void setErrorCode(String value) { 
        this.errorCode = value; 
    } 
 
    /** 
     * Gets the value of the severity property. 
     *  
     * @return 
     *     possible object is 
     *     {@link String } 
     *      
     */ 
    public String getSeverity() { 
        if (severity == null) { 
            return "urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:Error"; 
        } else { 
            return severity; 
        } 
    } 
 
    /** 
     * Sets the value of the severity property. 
     *  
     * @param value 
     *     allowed object is 
     *     {@link String } 
     *      
     */ 
    public void setSeverity(String value) { 
        this.severity = value; 
    } 
 
    /** 
     * Gets the value of the location property. 
     *  
     * @return 
     *     possible object is 
     *     {@link String } 
     *      
     */ 
    public String getLocation() { 
        return location; 
    } 
 
    /** 
     * Sets the value of the location property. 
     *  
     * @param value 
     *     allowed object is 
     *     {@link String } 
     *      
     */ 
    public void setLocation(String value) { 
        this.location = value; 
    } 
 
} 
